Repository ASFHyP3/its-live-monitoring, pull requests merged in 2024-04, with the labels that each got.

#41 Add automated dead letter queue MM updates
  .github/actions/deploy/action.yml
  Makefile
  cloudformation.yml
  requirements-all.txt
  requirements-status-messages.txt
  status-messages/cloudformation.yml
  status-messages/src/status_messages.py
Labels: bumpless

#45 fix makefile
  Makefile
Labels: bumpless

#48 Use roles-as-code b/c of JPL shenanigans
  status-messages/cloudformation.yml
Labels: bumpless

#49 fix typo
  status-messages/cloudformation.yml
Labels: bumpless

#50 Specify queue name and add emoji
  status-messages/src/status_messages.py
Labels: bumpless

#51 Futz with message
  status-messages/src/status_messages.py
Labels: bumpless

#46 Release v0.2.0 -- MM status messages
  .github/actions/deploy/action.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-test.yml
  CHANGELOG.md
  Makefile
  README.md
  cloudformation.yml
  requirements-all.txt
  requirements-status-messages.txt
  status-messages/cloudformation.yml
  status-messages/src/status_messages.py
Labels: minor

#53 Release v0.3.0 -- MM bot
  CHANGELOG.md
  cloudformation.yml
  landsat/src/main.py
  status-messages/cloudformation.yml
  status-messages/src/status_messages.py
Labels: minor

#54 Modified Test to Use hyp3_sdk Instead of a JSON File
  tests/data/job1.json
  tests/data/job2.json
  tests/landsat/test_main.py
Labels: enhancement

#42 loose the limit of only processing the NADIR scenes
  CHANGELOG.md
  landsat/src/main.py
  tests/data/scene1_pair.parquet
  tests/data/scene1_return_itemcollection.json
  tests/landsat/test_main.py
Labels: patch

#58 Fix off-nadir handling for Landsat
  landsat/src/main.py
Labels: bug, bumpless

#61 S2 low latency jz v2 solve the cross-reference of the scene ID
  landsat/src/main.py
  sentinel2/src/main.py
  tests/data/landsat/landsat_scene1_pairs.parquet
  tests/data/landsat/landsat_scene1_return_itemcollection.json
  tests/data/sentinel2/S2B_13CES_20200315_0_L1C_pages.json
  tests/data/sentinel2/S2B_13CES_20200315_0_L1C_pairs.parquet
  tests/data/sentinel2/S2B_13CES_20200315_0_L1C_scene.json
  tests/landsat/test_main.py
  tests/sentinel2/test_main.py
Labels: bumpless

#62 Refactor tests
  .github/workflows/create-jira-issue.yml
  .github/workflows/tests.yml
  ruff.toml
  tests/conftest.py
  tests/data/scene1_pair.parquet
  tests/data/scene1_return_itemcollection.json
  tests/landsat/test_main.py
Labels: bumpless

#64 Add tests for off-nadir scenes
  tests/landsat/test_main.py
Labels: bumpless

#56 Release v0.4.0 -- Off-nadir Landsat
  .github/workflows/create-jira-issue.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  landsat/src/main.py
  ruff.toml
  tests/conftest.py
  tests/integration/landsat-l8-off-nadir-no-pairs.json
  tests/integration/landsat-l8-off-nadir-valid.json
  tests/landsat/test_main.py
Labels: minor
