Repository ASFHyP3/its-live-monitoring, pull requests merged in 2024-05, with the labels that each got.

#68 Update dependabot.yml to weekly
  .github/dependabot.yml
Labels: bumpless

#70 Sentinel-2 Sample Messages for Integration Testing
  cloudformation.yml
  tests/integration/sentinel2-not-over-ice.json
  tests/integration/sentinel2-valid-1.json
  tests/integration/sentinel2-valid-2.json
Labels: bumpless, enhancement

#73 Fix Sentinel-2 STAC API Pagination Issue
  cloudformation.yml
  its_live_monitoring/src/sentinel2.py
Labels: bumpless

#76 Various Sentinle-2 fixes
  Makefile
  README.md
  docs/deadletter_queue_playbook.md
  its_live_monitoring/src/landsat.py
  its_live_monitoring/src/sentinel2.py
  requirements-all.txt
  requirements-its_live_monitoring.txt
  ruff.toml
Labels: bug, bumpless

#75 Release v0.5.0 - Sentinel-2
  .github/actions/deploy/action.yml
  .github/dependabot.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-test.yml
  CHANGELOG.md
  Makefile
  README.md
  cloudformation.yml
  docs/deadletter_queue_playbook.md
  its_live_monitoring/src/constants.py
  its_live_monitoring/src/landsat.py
  its_live_monitoring/src/landsat_tiles_to_process.json
  its_live_monitoring/src/main.py
  its_live_monitoring/src/sentinel2.py
  its_live_monitoring/src/sentinel2_tiles_to_process.json
  requirements-all.txt
  requirements-its_live_monitoring.txt
  ruff.toml
  tests/integration/sentinel2-not-over-ice.json
  tests/integration/sentinel2-valid-1.json
  tests/integration/sentinel2-valid-2.json
  tests/its_live_monitoring/test_landsat.py
  tests/its_live_monitoring/test_main.py
  tests/its_live_monitoring/test_sentinel2.py
Labels: minor

#79 Improve Sentinel-2 STAC search geometry
  its_live_monitoring/src/sentinel2.py
  requirements-its_live_monitoring.txt
  tests/conftest.py
  tests/its_live_monitoring/test_sentinel2.py
Labels: bumpless, enhancement

#80 Try two stage deploy for EU subscription
  .github/actions/deploy/action.yml
  .github/workflows/deploy-test.yml
  Makefile
  cloudformation.yml
  its_live_monitoring/cloudformation-subscribe-in-eu.yml
Labels: bug, bumpless

#82 Release v0.5.1 - Sentinel-2 attempt 2
  .github/actions/deploy/action.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-test.yml
  .github/workflows/tag-version.yml
  CHANGELOG.md
  Makefile
  cloudformation.yml
  its_live_monitoring/cloudformation-subscribe-in-eu.yml
  its_live_monitoring/src/sentinel2.py
  requirements-its_live_monitoring.txt
  tests/conftest.py
  tests/its_live_monitoring/test_sentinel2.py
Labels: patch

#85 Fix tag-version.yml
  .github/workflows/tag-version.yml
Labels: CI/CD, bug, bumpless

#89 Data coverage check
  CHANGELOG.md
  its_live_monitoring/src/constants.py
  its_live_monitoring/src/landsat.py
  its_live_monitoring/src/main.py
  its_live_monitoring/src/sentinel2.py
  tests/its_live_monitoring/test_landsat.py
  tests/its_live_monitoring/test_sentinel2.py
Labels: patch

#95 S2 Data Coverage Fixes and Refactors
  CHANGELOG.md
  its_live_monitoring/src/main.py
  its_live_monitoring/src/sentinel2.py
  tests/conftest.py
  tests/its_live_monitoring/test_sentinel2.py
Labels: bumpless
