Repository ASFHyP3/its-live-monitoring, pull requests merged in 2024-06, with the labels that each got.

#98 Fix `qualifies_for_sentinel2_processing` kwarg
  its_live_monitoring/src/landsat.py
  its_live_monitoring/src/main.py
  its_live_monitoring/src/sentinel2.py
Labels: bumpless

#102 Replace s3:// with https://roda... to Fix 403 Issue
  its_live_monitoring/src/sentinel2.py
  tests/its_live_monitoring/test_sentinel2.py
Labels: bumpless

#103 rename integration files for S2 changes and log ESA ID instead of E84 ID
  its_live_monitoring/src/sentinel2.py
  tests/integration/sentinel2-not-enough-data-coverage.json
  tests/integration/sentinel2-valid.json
  tests/its_live_monitoring/test_sentinel2.py
Labels: bumpless

#94 Release 0.5.2
  .github/workflows/tag-version.yml
  CHANGELOG.md
  its_live_monitoring/src/constants.py
  its_live_monitoring/src/landsat.py
  its_live_monitoring/src/main.py
  its_live_monitoring/src/sentinel2.py
  requirements-its_live_monitoring.txt
  tests/conftest.py
  tests/integration/sentinel2-not-enough-data-coverage.json
  tests/integration/sentinel2-valid.json
  tests/its_live_monitoring/test_landsat.py
  tests/its_live_monitoring/test_sentinel2.py
Labels: patch

#104 downgrade SDK due to timeout bug
  CHANGELOG.md
  requirements-its_live_monitoring.txt
Labels: bug

#106 Release v0.5.3 - hyP3 SDK downgrade
  .github/workflows/changelog.yml
  .github/workflows/create-jira-issue.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release-checklist-comment.yml
  .github/workflows/release.yml
  .github/workflows/static-anaysis.yml
  .github/workflows/tag-version.yml
  CHANGELOG.md
  requirements-its_live_monitoring.txt
Labels: patch

#109 pin packages in requirements-all.txt
  requirements-all.txt
Labels: bumpless

#114 add --no-compile to pip install to reduce size of lambda deployment zips
  Makefile
Labels: bumpless

#112 Release v0.5.4
  CHANGELOG.md
  Makefile
  cloudformation.yml
  its_live_monitoring/src/main.py
  its_live_monitoring/src/sentinel2.py
  requirements-all.txt
  requirements-its_live_monitoring.txt
  tests/integration/sentinel2-reprocessing-N0500.json
  tests/its_live_monitoring/test_sentinel2.py
Labels: patch
