Repository ASFHyP3/its-live-monitoring, pull requests merged in 2024-03, with the labels that each got.

#13 fix path to cloudformation
  .github/actions/deploy/action.yml
Labels: bumpless

#15 update integration test payloads
  tests/integration/landsat-l8-not-over-ice.json
  tests/integration/landsat-l8-too-many-clouds.json
  tests/integration/landsat-l8-valid.json
  tests/integration/landsat-l9-wrong-product-level.json
  tests/integration/sns-message-landsat-l9-valid.txt
Labels: bumpless

#17 Refine criteria for which reference/secondary scenes qualify for processing
  landsat/cloudformation.yml
  landsat/src/main.py
Labels: bumpless

#18 add dead letter queue as an offramp for messages that cannot be processed
  landsat/cloudformation.yml
Labels: bumpless

#19 implement batchItemFailures so only failures are returned to the queue
  landsat/cloudformation.yml
  landsat/src/main.py
  requirements-landsat.txt
Labels: bumpless

#24 prune to 50 random landsat tiles for production pilot
  landsat/src/landsat_tiles_to_process.json
Labels: bumpless

#26 Release 0.0.1
  .github/CODEOWNERS
  .github/actions/deploy/action.yml
  .github/dependabot.yml
  .github/workflows/changelog.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-test.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release-checklist-comment.yml
  .github/workflows/release.yml
  .github/workflows/static-anaysis.yml
  .gitignore
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  Makefile
  README.md
  cloudformation.yml
  environment.yml
  landsat/cloudformation.yml
  landsat/src/landsat_tiles_to_process.json
  landsat/src/main.py
  requirements-all.txt
  requirements-landsat.txt
  ruff.toml
  src/main.py
  tests/integration/landsat-l8-not-over-ice.json
  tests/integration/landsat-l8-too-many-clouds.json
  tests/integration/landsat-l8-valid.json
  tests/integration/landsat-l9-wrong-product-level.json
Labels: patch

#29 add integration test for RT scene
  tests/integration/landsat-l9-wrong-tier.json
Labels: bumpless

#30 Release v0.0.2
  CHANGELOG.md
  landsat/cloudformation.yml
  tests/integration/landsat-l9-wrong-tier.json
Labels: patch

#33 Release v0.0.3 -- All land-ice Landsat tiles
  CHANGELOG.md
  landsat/src/landsat_tiles_to_process.json
Labels: patch

#39 Fix cloud cover requirements
  CHANGELOG.md
  landsat/src/main.py
  tests/landsat/test_main.py
Labels: bug

#37 Release v0.1.0
  .github/actions/deploy/action.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-test.yml
  CHANGELOG.md
  landsat/cloudformation.yml
  landsat/src/main.py
  ruff.toml
  tests/landsat/test_main.py
Labels: minor

#40 makefile integration target to submit all the integration payloads
  Makefile
  README.md
Labels: bumpless
